---
title: "Most Popular Bike Routes in Los Angeles"
output: html_document
---

# import data
```{r}

trips = read.csv("./data/metro-trips-2022-q2.csv")
stations = read.csv("./data/metro-bike-share-stations-2022-10-01.csv")

# remove station 3000 (obselete)
trips<-trips[!(trips$start_station== 3000 | trips$end_station== 3000),]

head(stations)
```

# Merge Lat and Long to Station Data
```{r}
# start and end stations are identical when taken uniquely so only start station IDs will be used
stations_2 = subset(trips,select= c("start_station","start_lat","start_lon"))
stations_2 = unique(stations_2)
colnames(stations_2) = c("station_id", "lat", "long")

```

```{r}

# Get a list of the station IDs within LA
s_LA <- unique(stations$station_id)
# Limit trips to those with both origin and destination within the s_LA subset
trips_LA <- trips[(trips$start_station %in% s_LA) & (trips$end_station %in%s_LA),]
# Create a table with origins and destination pairs
OD_trips_LA <- table(trips$start_station,trips$end_station)
# View the top six rows
head(OD_trips_LA)

```


```{r}

# Create a data frame of the OD pairs
OD_trips_LA_Narrow <- data.frame(OD_trips_LA)
# Create sensible column names
colnames(OD_trips_LA_Narrow) <- c("Origin","Destination","Trips")

```

```{r}

# Sorts the trips in decending order
OD_trips_LA_Narrow <- OD_trips_LA_Narrow[order(OD_trips_LA_Narrow$Trips,decreasing = TRUE),]

# Get the top 10 trips
top10 <- OD_trips_LA_Narrow[OD_trips_LA_Narrow$Origin != OD_trips_LA_Narrow$Destination,]
All_Flows = top10
top10 <- top10[1:10,]
All_Flows = All_Flows[1:1000,]                                              
```

## Merge Origin Coordinates
```{r}
# Add origin co-ordinates
top10 <- merge(top10,stations_2, by.x="Origin",by.y="station_id", all.x=TRUE)
All_Flows <- merge(All_Flows,stations_2, by.x="Origin",by.y="station_id", all.x=TRUE)

# Remove unwanted columns
top10 <- subset(top10, select=c("Origin","Destination","Trips","lat","long"))
All_Flows <- subset(All_Flows, select=c("Origin","Destination","Trips","lat","long"))
# Change column names
colnames(top10) <- c("Origin","Destination","Trips","O_lat","O_long")
colnames(All_Flows) <- c("Origin","Destination","Trips","O_lat","O_long")

```

## Merge Destination Coordinates
```{r}
# Add origin co-ordinates
top10 <- merge(top10,stations_2, by.x="Destination",by.y="station_id", all.x=TRUE)
All_Flows <- merge(All_Flows,stations_2, by.x="Destination",by.y="station_id", all.x=TRUE)

# Change column names
colnames(top10) <- c("Origin","Destination","Trips","O_lat","O_long","D_lat", "D_long")
colnames(All_Flows) <- c("Origin","Destination","Trips","O_lat","O_long","D_lat", "D_long")

```



# get ggmap
```{r}
library(ggmap)
register_google(key = "AIzaSyBhHpnrFuM8iu5oXrJvmyvCDt_6tlTyZ0k")


# Get background map for Los Angeles
LA <- get_map(location = "losangeles", zoom = 10, color = "bw")
# Basic point plot of the bike stations
ggmap(LA) + geom_point(data = stations_2, aes(x = long, y = lat, colour =
"red")) +
theme_bw() +
theme(axis.line = element_blank(),
 axis.text = element_blank(),
 axis.title=element_blank(),
 axis.ticks = element_blank(),
 legend.key = element_blank(),
 legend.position="none",
 panel.grid.major = element_blank(),
 panel.grid.minor = element_blank(),
 panel.border = element_blank(),
 panel.background = element_blank())


```

# Visualizing individual routes
```{r}
# Install package
#install.packages("googleway")
# Load package
library(googleway)
# Set the API key
key <- "AIzaSyBhHpnrFuM8iu5oXrJvmyvCDt_6tlTyZ0k" 
# For this you will need to get a [Google maps API](https://developers.google.com/maps/documentation/directions/) key.

# Using the first origin/destination
x <- 3 # You can change this between 1 - 10 to view each of the routes
origin <- c(top10[x,"O_lat"],top10[x,"O_long"])
destination <- c(top10[x,"D_lat"],top10[x,"D_long"])
# get the directions from Google Maps API

res <- google_directions(origin = origin,destination = destination, key = key, mode= "bicycling")
# Convert the results to co-ordinates
df_polyline <- decode_pl(res$routes$overview_polyline$points)
# See the top six rows
head(df_polyline)


```


```{r}

tmp <- data.frame(lat = numeric(0), lon = numeric(0), ID = numeric(0), Trips= numeric(0))
# Make sure you run all code lines within the for loop below
for (x in 1:nrow(top10)) {
 # Get origins and destinations
 origin <- c(top10[x,"O_lat"],top10[x,"O_long"])
 destination <- c(top10[x,"D_lat"],top10[x,"D_long"])

 # get the directions from Google Maps API
  res <- suppressWarnings(google_directions(origin = origin, destination = destination, key = key, mode= "bicycling"))

 # Convert the results to co-ordinates
 df_polyline <- decode_pl(res$routes$overview_polyline$points)

 # Add a route ID and Trips to the data frame
 df_polyline$ID <- x
 df_polyline$Trips <- top10[x,"Trips"]

 # Append the results to the tmp object
 tmp <- rbind(tmp,df_polyline)
}

```

```{r}

all_flows <- data.frame(lat = numeric(0), lon = numeric(0), ID = numeric(0), Trips= numeric(0))
# Make sure you run all code lines within the for loop below
for (x in 1:nrow(All_Flows)) {
 # Get origins and destinations
 origin <- c(All_Flows[x,"O_lat"],All_Flows[x,"O_long"])
 destination <- c(All_Flows[x,"D_lat"],All_Flows[x,"D_long"])

 # get the directions from Google Maps API
 res <- suppressWarnings(google_directions(origin = origin,destination =destination,key = key, mode= "bicycling"))
  
 # Convert the results to co-ordinates
 df_polyline <- decode_pl(res$routes$overview_polyline$points)

 # Add a route ID and Trips to the data frame
 df_polyline$ID <- x
 df_polyline$Trips <- All_Flows[x,"Trips"]

 # Append the results to the tmp object
 all_flows <- rbind(all_flows,df_polyline)
}

```


## Individual Routes Plot
Visualizing all the flows of bike routes 
```{r}
LA <- get_map(location = "santamonica", zoom = 12, color = "bw")

ggmap(LA) +
 geom_path(aes(x = lon, y = lat, group = ID), data= all_flows, size = all_flows$Trips/ 1000)+
 geom_path(aes(x = lon, y = lat,color = as.factor(ID)), size = 1 , data = (tmp[tmp$ID == c(1),]), lineend = "round") #+ 
 #geom_point(data  = stations_2, aes(long,lat), colour = "red") +
 #geom_text(data = stations_2,aes(x = long, y = lat, label = station_id), check_overlap = TRUE, colour="#FFFFFF",hjust=-0.6)



```
## Top 10 Bike Routes PLot
Visualizing all bike flows and the top 10 routes. Stil hard to see since lots of overlapping routes. 
```{r}
LA <- get_map(location = "santamonica", zoom = 12, color = "bw")

plot  = ggmap(LA) +
  geom_path(aes(x = lon, y = lat, group = ID), data= all_flows, size = 0.5)+
  geom_path(aes(x = lon, y = lat,color = as.factor(ID)), position = "jitter" , size = 1,data = tmp)+
  geom_point(data  = stations_2, aes(long,lat), colour = "red") +
  ggtitle("Top 10 Metro Bike Routes")+
  theme (
 axis.text = element_blank (),
 axis.title = element_blank (),
 axis.ticks = element_blank ()
 )
  
  
plot = plot +  labs(color = "Top Bike Trips")
  




# make plotly
library(plotly)
png(filename="LA_top10BikeRoutes.png", width=1000, height=1000)

p = ggplotly(plot)
p
htmlwidgets::saveWidget(as_widget(p), "index.html")
dev.off()
```



## All Bike Flows Plot 
```{r}
png(filename="LA_all_flows.png")


plot = ggmap(LA,darken = 0.8) +
 geom_path(aes(x = lon, y = lat, group = ID,colour = all_flows$Trips), data
= all_flows, size = all_flows$Trips/400) +
 scale_colour_gradient(low="#900C3F", high="#FFC300",name="Trips") +
 geom_point(data=stations_2, aes(long, lat),colour="red") +
 geom_text(data = stations_2,aes(x = long, y = lat, label = station_id), check_overlap = TRUE, colour="#FFFFFF",hjust=-0.6) +
 theme (
 axis.text = element_blank (),
 axis.title = element_blank (),
 axis.ticks = element_blank ()
 )+ggtitle("All Bike Route Flows")


dev.off()
plot

```

